
[font]
size = 18

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[scrolling]
history = 0

[window]
opacity = 1
option_as_alt = "Both"

[general]
import = ["/Users/deebakkarthi/.config/alacritty/modus_vivendi.toml"]


[cursor.style]
shape = "Block"
blinking = "Off"
